services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: ghcr.io/sunmh207/ai-codereview-gitlab:1.3.9
    ports:
      - "5001:5001"
    volumes:
      # - ./data:/app/data
      - ./log:/app/log
    env_file:
      - ./conf/.env.prd
    restart: unless-stopped